name: dart

on:
  push:
    branches: [develop]

  pull_request:
    branches: [develop]

jobs:
  checks:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - run: dart pub get
      - run: dart test
      - run: dart analyze
